// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import BackController from "./back_controller"
application.register("back", BackController)

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import LoadMoreTableController from "./load_more_table_controller"
application.register("load-more-table", LoadMoreTableController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)

import OeuvresCounterController from "./oeuvres_counter_controller"
application.register("oeuvres-counter", OeuvresCounterController)

import ProgressFormController from "./progress_form_controller"
application.register("progress-form", ProgressFormController)

import RecaptchaController from "./recaptcha_controller"
application.register("recaptcha", RecaptchaController)

import ReferenceScrollController from "./reference_scroll_controller"
application.register("reference-scroll", ReferenceScrollController)

import ScrollHorizontalController from "./scroll_horizontal_controller"
application.register("scroll-horizontal", ScrollHorizontalController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import ShowPasswordController from "./show_password_controller"
application.register("show-password", ShowPasswordController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TabsSearchController from "./tabs_search_controller"
application.register("tabs-search", TabsSearchController)

import UniqueSelectController from "./unique_select_controller"
application.register("unique-select", UniqueSelectController)

import ValidationOverlayController from "./validation_overlay_controller"
application.register("validation-overlay", ValidationOverlayController)
