#!/bin/bash
# Checklist final avec commandes prêtes à exécuter
# Copier-coller chaque section dans votre terminal

cd /Users/thomasriq/omniscient_design

echo "=====================================aste"
echo "🚀 CHECKLIST DE MIGRATION FINAL"
echo "====================================="
echo ""

# ÉTAPE 1: Vérifier les dépendances
echo "✅ ÉTAPE 1: Vérifier l'état du projet"
echo "--------------------------------------"
echo ""
echo "Commandes à exécuter:"
echo "1. Vérifier la branche Git:"
echo "   git status"
echo ""
echo "2. Backup de la base de données:"
echo "   pg_dump -U postgres omniscient_design_development > backup_$(date +%Y%m%d_%H%M%S).sql"
echo ""
echo "3. Vérifier l'état des migrations:"
echo "   rails db:migrate:status | tail -20"
echo ""
echo "---"
echo ""

# ÉTAPE 2: Test syntaxe
echo "✅ ÉTAPE 2: Test de syntaxe Rails"
echo "--------------------------------------"
echo ""
echo "Commandes à exécuter:"
echo "1. Vérifier la syntaxe des routes:"
echo "   rails routes | grep -i reference | head -20"
echo ""
echo "2. Précompiler les assets:"
echo "   rails assets:precompile"
echo ""
echo "---"
echo ""

# ÉTAPE 3: Exécuter migrations
echo "✅ ÉTAPE 3: Exécuter les migrations"
echo "--------------------------------------"
echo ""
echo "⚠️  AVANT TOUTE CHOSE - CRÉER UN BACKUP:"
echo "   rails db:structure:dump"
echo ""
echo "Commande migration:"
echo "   rails db:migrate"
echo ""
echo "Puis vérifier:"
echo "   rails db:migrate:status | tail -5"
echo ""
echo "---"
echo ""

# ÉTAPE 4: Tests
echo "✅ ÉTAPE 4: Tester en local"
echo "--------------------------------------"
echo ""
echo "Lancer le serveur:"
echo "   rails s"
echo ""
echo "Tests à faire dans navigateur:"
echo "   1. http://localhost:3000/fr/oeuvres → doit rediriger à /fr/references (301)"
echo "   2. http://localhost:3000/en/oeuvres → doit rediriger à /en/references (301)"
echo "   3. http://localhost:3000/fr/references → doit charger normalement"
echo "   4. http://localhost:3000/admin/references/verbs → doit charger"
echo ""
echo "Vérifier les redirects avec:"
echo "   curl -I http://localhost:3000/fr/oeuvres"
echo "   (Doit montrer: HTTP/1.1 301 Moved Permanently)"
echo ""
echo "---"
echo ""

# ÉTAPE 5: Erreurs
echo "✅ ÉTAPE 5: Chercher les erreurs restantes"
echo "--------------------------------------"
echo ""
echo "Commandes de vérification:"
echo "   grep -r 'class Oeuvre' app/ --include='*.rb' | grep -v moved_"
echo "   grep -r \"@oeuvre\" app/ --include='*.rb' --include='*.erb' | wc -l"
echo "   grep -r ':oeuvre' config/routes.rb | wc -l"
echo ""
echo "---"
echo ""

# ÉTAPE 6: Commit
echo "✅ ÉTAPE 6: Commit Git"
echo "--------------------------------------"
echo ""
echo "Commandes:"
echo "   git add -A"
echo "   git commit -m '🔧 Refactor: Rename oeuvres to references with 301 SEO redirects'"
echo "   git log --oneline -1  # vérifier le commit"
echo ""
echo "---"
echo ""

# ÉTAPE 7: Déploiement
echo "✅ ÉTAPE 7: Déployer"
echo "--------------------------------------"
echo ""
echo "IMPORTANT - Déploiement pas à pas:"
echo ""
echo "Sur production:"
echo "   1. SSH sur production"
echo "   2. Backup de la BD:"
echo "      pg_dump -U user db > backup_$(date +%Y%m%d).sql"
echo "   3. Pull le code:"
echo "      git pull origin main"
echo "   4. Installer dépendances:"
echo "      bundle install"
echo "   5. Exécuter migrations:"
echo "      rails db:migrate RAILS_ENV=production"
echo "   6. Compiler assets:"
echo "      rails assets:precompile RAILS_ENV=production"
echo "   7. Redémarrer le serveur:"
echo "      systemctl restart puma  (ou selon votre config)"
echo "   8. Vérifier les logs:"
echo "      tail -f log/production.log"
echo ""
echo "---"
echo ""

# ÉTAPE 8: Post-déploiement
echo "✅ ÉTAPE 8: Après déploiement"
echo "--------------------------------------"
echo ""
echo "À faire:"
echo "   1. Tester les URLs en production"
echo "   2. Vérifier Google Search Console"
echo "   3. Monitor les logs pour erreurs"
echo "   4. Attendre 24-48h pour la stabilisation SEO"
echo ""
echo "Commandes de monitoring:"
echo "   tail -f log/production.log | grep -i 'reference\\|oeuvre'"
echo ""
echo "---"
echo ""

echo "✅ MIGRATION COMPLÈTE!"
echo ""
echo "📚 Voir également:"
echo "   - MIGRATION_GUIDE_FR.md"
echo "   - SEO_REDIRECTS_EXPLAINER_FR.md"
echo ""
