# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '2aa1f08e5481b9f62381406fc517037e'
  config.secret_key = 'b5e19dbfa0a1bdccc723b7521232a47c'
  config.default_from = 'contact@omniscientdesign.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
