development:
  recaptcha_site_key: "6LfLCaMqAAAAAGdWN3_BGZL0TuM1Zm_N3sTX_wLm"
  recaptcha_secret_key: "6LfLCaMqAAAAABqdWSxN5158_BhG7cGjyzsQ5fEE"

production:
  recaptcha_site_key: "6LfLCaMqAAAAAGdWN3_BGZL0TuM1Zm_N3sTX_wLm"
  recaptcha_secret_key: "6LfLCaMqAAAAABqdWSxN5158_BhG7cGjyzsQ5fEE"
